apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: core
    newName: ghcr.io/ggingggang/k8s-test-core-server
    newTag: 8f14cb4beffca8be6aae88f328d470489c8a8eea
