apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: core
    newName: ghcr.io/ggingggang/k8s-test-core-server
    newTag: de13ef9474c5e0af62f3bf6d63e68924e07ba4c2
